name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      NUGET_TOKEN: ${{ secrets.YDB_PLATFORM_NUGET_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x 
      - name: Build
        run: |
          cd src
          dotnet build --configuration Release 
          dotnet pack -c Release -o out /p:Version=$VERSION
          dotnet nuget push out/Ydb.Sdk.Yc.Auth.$VERSION.nupkg --skip-duplicate --api-key $NUGET_TOKEN --source https://api.nuget.org/v3/index.json
